[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
poem = { version = "1.3" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
store = { path = "../store"}
dotenvy = "0.15.7"
